// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/devices" | "/o/[id]" | "/s/[token]"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/auth/token" | "/api/config" | "/api/devices" | "/api/diagnostics" | "/api/files/[id]" | "/api/mobile" | "/api/objects" | "/api/objects/[id]" | "/api/public/[token]/file" | "/api/public/[token]/unlock" | "/api/setup" | "/api/share-target" | "/api/shares" | "/api/shares/[id]" | "/api/status"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/token": {}
  "/api/config": {}
  "/api/devices": {}
  "/api/diagnostics": {}
  "/api/files/[id]": { "id": string; }
  "/api/mobile": {}
  "/api/objects": {}
  "/api/objects/[id]": { "id": string; }
  "/api/public/[token]/file": { "token": string; }
  "/api/public/[token]/unlock": { "token": string; }
  "/api/setup": {}
  "/api/share-target": {}
  "/api/shares": {}
  "/api/shares/[id]": { "id": string; }
  "/api/status": {}
  "/devices": {}
  "/o/[id]": { "id": string; }
  "/s/[token]": { "token": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
