"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Archive, ArrowUpRight, Check, Code2, Copy, Download, File, FileText, FolderOpen, LayoutGrid, Link2, LogOut, Menu, Pin, Plus, Search, Settings, Trash2, Upload, X } from "lucide-react";
type Obj={id:string;type:"snippet"|"file"|"link";name:string;content?:string;language?:string;url?:string;mimeType?:string;sizeBytes?:number;pinned:boolean;createdAt:string;deletedAt?:string};
type Config={initialized:boolean;modules:{snippets:boolean;files:boolean;links:boolean;board:boolean};exposure:string;theme:string;maxSizeMb:number;trashRetentionDays:number};
const api=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Something went wrong");return d};
const size=(n=0)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const ago=(s:string)=>{const n=(Date.now()-new Date(s).getTime())/1000;return n<60?"just now":n<3600?`${Math.floor(n/60)}m ago`:n<86400?`${Math.floor(n/3600)}h ago`:new Date(s).toLocaleDateString(undefined,{month:"short",day:"numeric"})};
const icons={snippet:Code2,file:FileText,link:Link2};
export default function Home(){
 const [state,setState]=useState<"loading"|"setup"|"login"|"app">("loading"),[config,setConfig]=useState<Config|null>(null),[username,setUsername]=useState(""),[objects,setObjects]=useState<Obj[]>([]),[view,setView]=useState("all"),[query,setQuery]=useState(""),[modal,setModal]=useState<null|"create"|"settings">(null),[toast,setToast]=useState("");
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2400)};
 const boot=useCallback(async()=>{const s=await api("/api/status");setConfig(s.config);setUsername(s.username||"");if(!s.initialized)setState("setup");else if(!s.authenticated)setState("login");else{setState("app");setObjects((await api(`/api/objects${view==="trash"?"?trash=true":""}`)).objects)}},[view]);
 useEffect(()=>{boot().catch(()=>setState("login"))},[boot]);
 const filtered=useMemo(()=>objects.filter(o=>(view==="all"||view==="trash"||o.type===view)&&(o.name+" "+(o.content||"")).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.pinned)-Number(a.pinned)),[objects,view,query]);
 if(state==="loading")return <Splash/>;if(state==="setup")return <Setup done={boot}/>;if(state==="login")return <Login done={boot}/>;
 const counts={all:objects.length,snippet:objects.filter(x=>x.type==="snippet").length,file:objects.filter(x=>x.type==="file").length,link:objects.filter(x=>x.type==="link").length};
 const pin=async(o:Obj)=>{await api(`/api/objects/${o.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({pinned:!o.pinned})});setObjects(x=>x.map(v=>v.id===o.id?{...v,pinned:!v.pinned}:v));flash(o.pinned?"Removed from Quick access":"Pinned to Quick access")};
 const remove=async(o:Obj,permanent=false)=>{await api(`/api/objects/${o.id}${permanent?"?permanent=true":""}`,{method:"DELETE"});setObjects(x=>x.filter(v=>v.id!==o.id));flash(permanent?"Permanently deleted":"Moved to trash")};
 const restore=async(o:Obj)=>{await api(`/api/objects/${o.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({restore:true})});setObjects(x=>x.filter(v=>v.id!==o.id));flash("Restored")};
 return <div className="app-shell"><aside className="sidebar"><Logo/><button className="new-btn" onClick={()=>setModal("create")}><Plus/>New object</button><nav><Nav active={view==="all"} onClick={()=>setView("all")} icon={<LayoutGrid/>} label="Everything" count={counts.all}/><p>Workspace</p>{config?.modules.snippets&&<Nav active={view==="snippet"} onClick={()=>setView("snippet")} icon={<Code2/>} label="Snippets" count={counts.snippet}/>} {config?.modules.files&&<Nav active={view==="file"} onClick={()=>setView("file")} icon={<File/>} label="Files" count={counts.file}/>} {config?.modules.links&&<Nav active={view==="link"} onClick={()=>setView("link")} icon={<Link2/>} label="Links" count={counts.link}/>}<p>Manage</p><Nav active={view==="trash"} onClick={()=>setView("trash")} icon={<Trash2/>} label="Trash"/><Nav active={false} onClick={()=>setModal("settings")} icon={<Settings/>} label="Settings"/></nav><div className="server"><span/><div><b>9t server</b><small>Online · port 3265</small></div></div></aside>
 <main className="workspace"><header className="topbar"><button className="mobile-menu"><Menu/></button><div className="search"><Search/><input placeholder="Search your workspace…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><div className="user"><span>{username.slice(0,2).toUpperCase()}</span><div><b>{username}</b><small>Administrator</small></div><button title="Sign out" onClick={async()=>{await api("/api/auth/logout",{method:"POST"});setState("login")}}><LogOut/></button></div></header><section className="content"><div className="title-row"><div><p className="crumb">9T / {view.toUpperCase()}</p><h1>{view==="all"?"Your workspace":view[0].toUpperCase()+view.slice(1)}</h1><p>{view==="trash"?"Items stay here until you permanently remove them.":`${filtered.length} ${filtered.length===1?"object":"objects"} available from all your devices.`}</p></div><button className="primary" onClick={()=>setModal("create")}><Plus/>Add new</button></div>
 {view==="all"&&objects.some(o=>o.pinned)&&<><SectionTitle title="Quick access" action="Pinned objects"/><div className="quick-grid">{objects.filter(o=>o.pinned).slice(0,4).map(o=><Card key={o.id} o={o} pin={pin} remove={remove}/>)}</div></>}<SectionTitle title={view==="trash"?"Trash":"Recent"} action={`${filtered.length} total`}/>{filtered.length?<div className="object-list">{filtered.map(o=><Row key={o.id} o={o} trash={view==="trash"} pin={pin} remove={remove} restore={restore}/>)}</div>:<Empty trash={view==="trash"} create={()=>setModal("create")}/>}</section></main>
 {modal==="create"&&<Create config={config!} close={()=>setModal(null)} saved={async()=>{setModal(null);await boot();flash("Object added")}}/>}{modal==="settings"&&<SettingsPanel config={config!} close={()=>setModal(null)} saved={async()=>{setModal(null);await boot();flash("Settings saved")}}/>}{toast&&<div className="toast"><Check/>{toast}</div>}</div>}
function Logo(){return <div className="logo"><img src="/9t-mark.svg" alt="9t"/><div><b>9t</b><small>workspace</small></div></div>};function Splash(){return <div className="center"><Logo/><div className="loader"/></div>}
function Nav(p:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string;count?:number}){return <button className={p.active?"nav active":"nav"} onClick={p.onClick}>{p.icon}<span>{p.label}</span>{p.count!==undefined&&<i>{p.count}</i>}</button>};function SectionTitle({title,action}:{title:string;action:string}){return <div className="section-title"><h2>{title}</h2><span>{action}</span></div>}
function Card({o,pin,remove}:{o:Obj;pin:(o:Obj)=>void;remove:(o:Obj)=>void}){const Icon=icons[o.type];return <div className="object-card"><div className={`type-icon ${o.type}`}><Icon/></div><button className="dots" onClick={()=>remove(o)}><Trash2/></button><div className="preview">{o.type==="snippet"?<code>{o.content?.slice(0,90)||"Empty snippet"}</code>:o.type==="link"?<span>{o.url}</span>:<FileText/>}</div><b>{o.name}</b><small>{o.type} · {ago(o.createdAt)}</small><button className="pin" onClick={()=>pin(o)}><Pin fill="currentColor"/>Pinned</button></div>}
function Row({o,trash,pin,remove,restore}:{o:Obj;trash:boolean;pin:(o:Obj)=>void;remove:(o:Obj,p?:boolean)=>void;restore:(o:Obj)=>void}){const Icon=icons[o.type],open=()=>o.type==="file"?location.href=`/api/files/${o.id}`:o.type==="link"?window.open(o.url,"_blank"):navigator.clipboard.writeText(o.content||"");return <div className="object-row"><div className={`type-icon ${o.type}`}><Icon/></div><div className="object-name"><b>{o.name}</b><small>{o.type==="file"?`${size(o.sizeBytes)} · `:o.type==="snippet"?`${o.language||"text"} · `:""}{ago(o.createdAt)}</small></div><div className="object-detail">{o.type==="snippet"?(o.content||"Empty").slice(0,54):o.type==="link"?o.url:o.mimeType}</div>{trash?<div className="row-actions"><button onClick={()=>restore(o)}>Restore</button><button className="danger" onClick={()=>remove(o,true)}>Delete</button></div>:<div className="row-actions"><button onClick={open}>{o.type==="snippet"?<Copy/>:o.type==="file"?<Download/>:<ArrowUpRight/>}</button><button className={o.pinned?"selected":""} onClick={()=>pin(o)}><Pin/></button><button onClick={()=>remove(o)}><Trash2/></button></div>}</div>}
function Empty({trash,create}:{trash:boolean;create:()=>void}){return <div className="empty"><div>{trash?<Archive/>:<FolderOpen/>}</div><h3>{trash?"Trash is empty":"Nothing here yet"}</h3><p>{trash?"Deleted objects will appear here.":"Add a file, snippet, or link to start your workspace."}</p>{!trash&&<button className="primary" onClick={create}><Plus/>Add your first object</button>}</div>}
function Setup({done}:{done:()=>void}){const [step,setStep]=useState(1),[user,setUser]=useState("admin"),[pass,setPass]=useState(""),[key,setKey]=useState(""),[mods,setMods]=useState({snippets:true,files:true,links:true,board:false}),[error,setError]=useState("");const submit=async()=>{try{await api("/api/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:user,password:pass,setupToken:key,modules:mods,exposure:"public"})});done()}catch(e){setError((e as Error).message)}};return <div className="onboard"><div className="onboard-aside"><Logo/><div><p>YOUR SPACE. YOUR RULES.</p><h1>One home for everything you move.</h1><span>Private, fast, and running on infrastructure you control.</span></div><small>9t · self-hosted workspace</small></div><div className="onboard-main"><div className="steps"><span className="on">1</span><i/><span className={step>=2?"on":""}>2</span></div>{step===1?<div className="setup-form"><p className="eyebrow">WELCOME TO 9T</p><h2>Shape your workspace</h2><p>Choose what you want close at hand. You can change this later.</p><div className="module-grid">{Object.keys(mods).map(k=><button key={k} onClick={()=>setMods(m=>({...m,[k]:!m[k as keyof typeof m]}))} className={mods[k as keyof typeof mods]?"module active":"module"}><span>{k==="snippets"?<Code2/>:k==="files"?<File/>:k==="links"?<Link2/>:<LayoutGrid/>}</span><b>{k}</b><small>{k==="snippets"?"Code and text":k==="files"?"Upload anything":k==="links"?"Save the web":"Arrange your home"}</small>{mods[k as keyof typeof mods]&&<Check className="check"/>}</button>)}</div><button className="primary wide" onClick={()=>setStep(2)}>Continue <ArrowUpRight/></button></div>:<div className="setup-form"><p className="eyebrow">SECURE YOUR WORKSPACE</p><h2>Create the administrator</h2><p>9t is public on this VPS, so every object is protected behind your login.</p><label>Setup key<input value={key} onChange={e=>setKey(e.target.value)} placeholder="Key supplied by the server owner"/></label><label>Username<input value={user} onChange={e=>setUser(e.target.value)}/></label><label>Password<input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="At least 8 characters"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary wide" onClick={submit}>Finish setup <Check/></button><button className="back" onClick={()=>setStep(1)}>Back</button></div>}</div></div>}
function Login({done}:{done:()=>void}){const [username,setUsername]=useState("admin"),[password,setPassword]=useState(""),[error,setError]=useState("");const submit=async(e:FormEvent)=>{e.preventDefault();try{await api("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});done()}catch(e){setError((e as Error).message)}};return <div className="login"><form onSubmit={submit}><Logo/><p className="eyebrow">WELCOME BACK</p><h1>Open your workspace.</h1><label>Username<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="form-error">{error}</div>}<button className="primary wide">Sign in <ArrowUpRight/></button><small>Connected to your self-hosted 9t server.</small></form></div>}
function Create({config,close,saved}:{config:Config;close:()=>void;saved:()=>void}){const types=Object.entries(config.modules).filter(([k,v])=>v&&k!=="board").map(([k])=>k.slice(0,-1)) as Obj["type"][],[type,setType]=useState(types[0]||"snippet"),[busy,setBusy]=useState(false),[error,setError]=useState("");const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);try{await api("/api/objects",{method:"POST",body:new FormData(e.currentTarget)});saved()}catch(e){setError((e as Error).message);setBusy(false)}};return <Modal title="Add to 9t" close={close}><div className="type-tabs">{types.map(t=><button type="button" className={type===t?"active":""} onClick={()=>setType(t)} key={t}>{t}</button>)}</div><form className="modal-form" onSubmit={submit}><input type="hidden" name="type" value={type}/><label>Name<input name="name" required autoFocus placeholder="Give it a useful name"/></label>{type==="snippet"&&<><label>Language<select name="language"><option>text</option><option>javascript</option><option>typescript</option><option>python</option><option>bash</option><option>json</option><option>css</option><option>sql</option></select></label><label>Content<textarea name="content" rows={9} required placeholder="Paste code, a command, or any text…"/></label></>}{type==="link"&&<label>URL<input name="url" type="url" required placeholder="https://…"/></label>}{type==="file"&&<label className="drop"><Upload/><b>Choose a file</b><span>Up to {config.maxSizeMb} MB</span><input name="file" type="file" required onChange={e=>{const f=e.target.files?.[0],n=e.currentTarget.form?.elements.namedItem("name") as HTMLInputElement;if(f&&!n.value)n.value=f.name}}/></label>}{error&&<div className="form-error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?"Saving…":"Add to workspace"}<ArrowUpRight/></button></form></Modal>}
function SettingsPanel({config,close,saved}:{config:Config;close:()=>void;saved:()=>void}){const [mods,setMods]=useState(config.modules),[max,setMax]=useState(config.maxSizeMb);const submit=async()=>{await api("/api/config",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({modules:mods,maxSizeMb:max})});saved()};return <Modal title="Settings" close={close}><div className="settings"><p className="eyebrow">MODULES</p>{Object.keys(mods).map(k=><label className="switch-row" key={k}><span><b>{k[0].toUpperCase()+k.slice(1)}</b><small>Show this module throughout 9t</small></span><input type="checkbox" checked={mods[k as keyof typeof mods]} onChange={e=>setMods(m=>({...m,[k]:e.target.checked}))}/></label>)}<p className="eyebrow space">STORAGE</p><label>Maximum upload size (MB)<input type="number" min="1" value={max} onChange={e=>setMax(+e.target.value)}/></label><div className="exposure"><span/><div><b>Public exposure</b><small>Authentication required · port 3265</small></div></div><button className="primary wide" onClick={submit}>Save settings <Check/></button></div></Modal>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
